
socket: "/tmp/pcc-gw.sock"

mainAccount:
  login: "..........@......com"
  password: "....."

subAccounts:
  - login: ".........@........."
    password: "....."
  - login: "......."
    password: "...."

delayedSubAccountsRegistration: False

autoUpdate: 60