#!/bin/bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd ) #"

cd $SCRIPT_DIR

IN="eLGate.service"
OUT="/etc/systemd/system/$IN"
VENV_PYTHON=$(realpath "$SCRIPT_DIR/..")/venv/bin/python
ELGATE_EP=$(realpath "$SCRIPT_DIR/../eLGate.py")
USER="root" #change me!

EXEC="$VENV_PYTHON $ELGATE_EP"

echo $EXEC

cat $IN | sed "s|<<<EXEC_PATH>>>|$EXEC|" | sed "s/<<<USER>>>/$USER/" > $OUT

systemctl daemon-reload
systemctl start $IN
systemctl enable $IN
